apiVersion: v1
kind: Service
metadata:
  name: webhook-agent
  namespace: webhook-pipeline
  labels:
    app: webhook-agent
    app.kubernetes.io/part-of: mem-dog-webhook-pipeline
spec:
  type: ClusterIP
  selector:
    app: webhook-agent
  ports:
    - port: 8080
      targetPort: 8080
      name: http
