apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: webhook-pipeline
  labels:
    app: nats
    app.kubernetes.io/part-of: mem-dog-webhook-pipeline
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    - port: 4222
      targetPort: 4222
      name: client
    - port: 8222
      targetPort: 8222
      name: monitoring
