apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data
  namespace: neo4j
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: mem-dog
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
