apiVersion: v1
kind: Secret
metadata:
  name: neo4j-auth
  namespace: neo4j
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: mem-dog
type: Opaque
data:
  NEO4J_AUTH: bmVvNGovbWVtZG9nX25lbzRq
