apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: neo4j
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: memdog
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: neo4j
  ports:
    - port: 7687
      targetPort: 7687
      name: bolt
    - port: 7474
      targetPort: 7474
      name: http
