apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-data
  namespace: mem-dog
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: mem-dog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
