apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: memdog
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: memdog
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ui
  ports:
    - port: 3000
      targetPort: 8080
      name: http
