apiVersion: v1
kind: Secret
metadata:
  name: nango-secrets
  namespace: nango
type: Opaque
stringData:
  NANGO_ENCRYPTION_KEY: "MkvkgMm5ZQVLex8lqXMDEC/QbSs/gX8hxuuji1NSqBw="
  NANGO_SECRET_KEY: "ncLyB5dUqjsoDzw6DHKeYj5CENL4I4C8SOcL8yMJp1U="
  NANGO_DB_PASSWORD: "NC50bjF23Dz9nYfZYJdG5g=="
  NANGO_DASHBOARD_PASSWORD: "7zxAnDcvZ8+9RHK3zMbCCw=="
