apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-webhook-gateway
  namespace: nango
  labels:
    app.kubernetes.io/part-of: mem-dog
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: webhook-gateway
  to:
    - group: ""
      kind: Service
