-- Seed agent_configs table with hardcoded defaults from webhook pipeline code
-- These are system defaults (user_id = NULL)

INSERT INTO agent_configs (config_id, agent_type, user_id, intro, system_prompt, output_schema, skills, model_tier, parameters, version)
VALUES
-- Small tier agents
('acfg_seed_json',        'json',        NULL, 'Analyse this JSON content thoroughly',        'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_csv',         'csv',         NULL, 'Analyse this CSV data thoroughly',            'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_yaml',        'yaml',        NULL, 'Analyse this YAML content thoroughly',        'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_xml',         'xml',         NULL, 'Analyse this XML document thoroughly',        'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_feed',        'feed',        NULL, 'Read and analyse this RSS/Atom feed thoroughly','You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_sensor',      'sensor',      NULL, 'Analyse this sensor telemetry thoroughly',    'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_iot_sensor',  'iot_sensor',  NULL, 'Analyse this IoT sensor telemetry thoroughly', 'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_gps',         'gps',         NULL, 'Analyse this GPS/location data thoroughly',   'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_biometric',   'biometric',   NULL, 'Analyse this biometric data thoroughly',      'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_log_stream',  'log_stream',  NULL, 'Read and analyse this streaming log data thoroughly','You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_archive',     'archive',     NULL, 'Analyse the contents of this archive thoroughly','You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),
('acfg_seed_binary_blob', 'binary_blob', NULL, 'Analyse this binary data thoroughly',         'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'small',  '{}', 1),

-- Medium tier agents
('acfg_seed_code',           'code',           NULL, 'Read and analyse this source code thoroughly',           'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_log_file',      'log_file',       NULL, 'Read and analyse this log file thoroughly',              'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_email',          'email',          NULL, 'Read and analyse this email thoroughly',                 'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_calendar',      'calendar',       NULL, 'Read and analyse these calendar events thoroughly',      'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_chat',           'chat',           NULL, 'Read and analyse this chat transcript thoroughly',       'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_channel_message','channel_message',NULL, 'Read and analyse this channel message thoroughly',      'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_html_doc',      'html_doc',       NULL, 'Extract the main content from this HTML and analyse it thoroughly','You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_markdown',      'markdown',       NULL, 'Read and analyse this Markdown document thoroughly',     'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_time_series',   'time_series',    NULL, 'Analyse this time series data thoroughly',               'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_vehicle_telemetry','vehicle_telemetry',NULL,'Analyse this vehicle telemetry data thoroughly',      'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_financial',     'financial',      NULL, 'Analyse this financial data thoroughly',                 'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_industrial',    'industrial',     NULL, 'Analyse this industrial data thoroughly',                'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),
('acfg_seed_infrastructure','infrastructure', NULL, 'Analyse this infrastructure data thoroughly',            'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1),

-- Large tier agents
('acfg_seed_web_page',      'web_page',       NULL, 'Read and analyse this web page content thoroughly',      'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_pdf',           'pdf',            NULL, 'Read and analyse this PDF document thoroughly',          'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_office_doc',    'office_doc',     NULL, 'Read and analyse this Office document thoroughly',       'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_image',         'image',          NULL, 'Look at this image carefully and analyse it thoroughly',  'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_image_batch',   'image_batch',    NULL, 'Look at these images carefully and analyse them thoroughly','You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_video_url',     'video_url',      NULL, 'Watch this video carefully and analyse it thoroughly',    'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"],"transcript":"string — Full verbatim transcript","scenes":["array of strings — Chronological scene descriptions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_video_stream',  'video_stream',   NULL, 'Watch this video carefully and analyse it thoroughly',    'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"],"transcript":"string — Full verbatim transcript","scenes":["array of strings — Chronological scene descriptions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_audio_url',     'audio_url',      NULL, 'Listen to this audio carefully and analyse it thoroughly', 'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"],"transcript":"string — Full verbatim transcript","scenes":["array of strings — Chronological scene descriptions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_audio_stream',  'audio_stream',   NULL, 'Listen to this audio carefully and analyse it thoroughly', 'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"],"transcript":"string — Full verbatim transcript","scenes":["array of strings — Chronological scene descriptions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_geospatial',    'geospatial',     NULL, 'Analyse this geospatial data thoroughly',                'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_lidar',         'lidar',          NULL, 'Analyse this LiDAR point cloud data thoroughly',         'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_model_3d',      'model_3d',       NULL, 'Analyse this 3D model data thoroughly',                  'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_medical_imaging','medical_imaging',NULL, 'Analyse this medical imaging data thoroughly',           'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_conferencing',  'conferencing',   NULL, 'Analyse this conferencing/meeting data thoroughly',      'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_satellite',     'satellite',      NULL, 'Analyse this satellite data thoroughly',                 'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),
('acfg_seed_scientific',    'scientific',     NULL, 'Analyse this scientific data thoroughly',                'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'large',  '{}', 1),

-- Special: url_download (no LLM analysis, just URL discovery)
('acfg_seed_url_download',  'url_download',   NULL, 'Read and analyse this downloaded content thoroughly',    'You are a data analysis assistant. You MUST respond with ONLY a valid JSON object — no markdown, no code fences, no preamble, no explanation. Output raw JSON and nothing else.', '{"category":"string — One domain label","entities":["array of strings — All named entities"],"keywords":["array of strings — 5-15 topical keywords"],"summary":"string — Comprehensive 3-5 sentence summary","queries":["array of strings — 5-8 natural language questions"]}', '[]', 'medium', '{}', 1)

ON CONFLICT (agent_type, user_id) DO NOTHING;
