apiVersion: apps/v1
kind: Deployment
metadata:
  name: nango-server
  namespace: nango
spec:
  template:
    spec:
      containers:
        - name: nango-server
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 384Mi
