apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-auth
  namespace: supabase
spec:
  template:
    spec:
      containers:
        - name: gotrue
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_PASSWORD
            - name: GOTRUE_API_HOST
              value: "0.0.0.0"
            - name: GOTRUE_API_PORT
              value: "9999"
            - name: API_EXTERNAL_URL
              value: "http://localhost:8000"
            - name: GOTRUE_DB_DRIVER
              value: postgres
            - name: GOTRUE_DB_DATABASE_URL
              value: "postgres://postgres:$(POSTGRES_PASSWORD)@supabase-db.supabase.svc.cluster.local:5432/postgres?search_path=auth"
            - name: GOTRUE_SITE_URL
              value: "http://localhost:3000"
            - name: GOTRUE_URI_ALLOW_LIST
              value: "http://localhost:3000,http://127.0.0.1:3000"
            - name: GOTRUE_DISABLE_SIGNUP
              value: "false"
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: JWT_SECRET
            - name: GOTRUE_JWT_EXP
              value: "3600"
            - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
              value: authenticated
            - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
              value: "true"
            - name: GOTRUE_MAILER_AUTOCONFIRM
              value: "true"
            - name: GOTRUE_EXTERNAL_PHONE_ENABLED
              value: "false"
            - name: GOTRUE_EXTERNAL_GOOGLE_ENABLED
              value: "false"
