apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-kong
  namespace: supabase
spec:
  template:
    spec:
      containers:
        - name: kong
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            tcpSocket:
              port: 8000
            failureThreshold: 30
            periodSeconds: 5
