apiVersion: v1
kind: Service
metadata:
  name: supabase-meta
  namespace: supabase
  labels:
    app.kubernetes.io/name: supabase-meta
    app.kubernetes.io/part-of: mem-dog
    app.kubernetes.io/component: supabase
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: supabase-meta
