apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-db-data
  namespace: supabase
  labels:
    app.kubernetes.io/name: supabase-db
    app.kubernetes.io/part-of: memdog
    app.kubernetes.io/component: supabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
