apiVersion: v1
kind: Service
metadata:
  name: supabase-rest
  namespace: supabase
  labels:
    app.kubernetes.io/name: supabase-rest
    app.kubernetes.io/part-of: memdog
    app.kubernetes.io/component: supabase
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: supabase-rest
