apiVersion: v1
kind: Service
metadata:
  name: supabase-realtime
  namespace: supabase
  labels:
    app.kubernetes.io/name: supabase-realtime
    app.kubernetes.io/part-of: memdog
    app.kubernetes.io/component: supabase
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: supabase-realtime
