'use client';

import { AISignature } from '@/types';

interface AISignatureDisplayProps {
  signature: AISignature;
  compact?: boolean;
}

/**
 * Displays AI provenance signature information.
 * Shows which AI system generated the content, when, and with what parameters.
 */
export function AISignatureDisplay({ signature, compact = false }: AISignatureDisplayProps) {
  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleString();
  };

  const getEngineIcon = (engine: string) => {
    switch (engine) {
      case 'openai':
        return '🤖';
      case 'gemini':
        return '✨';
      case 'ollama':
        return '🦙';
      case 'litellm':
        return '🔗';
      default:
        return '🤖';
    }
  };

  const getEngineLabel = (engine: string) => {
    switch (engine) {
      case 'openai':
        return 'OpenAI';
      case 'gemini':
        return 'Google Gemini';
      case 'ollama':
        return 'Ollama';
      case 'litellm':
        return 'LiteLLM';
      default:
        return engine;
    }
  };

  if (compact) {
    return (
      <div className="ai-signature-compact">
        <span className="ai-signature-badge" title={`Generated by ${getEngineLabel(signature.ai_engine)} (${signature.model_name})`}>
          {getEngineIcon(signature.ai_engine)} {signature.model_name}
          {signature.key_mode === 'system' && <span className="key-mode-badge system">System</span>}
          {signature.key_mode === 'custom' && <span className="key-mode-badge custom">Custom</span>}
        </span>
        <style jsx>{`
          .ai-signature-compact {
            display: inline-flex;
            align-items: center;
            gap: 0.5rem;
          }
          .ai-signature-badge {
            display: inline-flex;
            align-items: center;
            gap: 0.25rem;
            padding: 0.25rem 0.5rem;
            background: var(--bg-secondary, #f5f5f5);
            border-radius: 4px;
            font-size: 0.75rem;
            color: var(--text-secondary, #666);
          }
          .key-mode-badge {
            padding: 0.125rem 0.375rem;
            border-radius: 3px;
            font-size: 0.625rem;
            font-weight: 600;
            text-transform: uppercase;
            margin-left: 0.25rem;
          }
          .key-mode-badge.system {
            background: #e3f2fd;
            color: #1565c0;
          }
          .key-mode-badge.custom {
            background: #f3e5f5;
            color: #7b1fa2;
          }
        `}</style>
      </div>
    );
  }

  return (
    <div className="ai-signature-full">
      <div className="ai-signature-header">
        <span className="ai-icon">{getEngineIcon(signature.ai_engine)}</span>
        <span className="ai-label">AI Generated Content</span>
      </div>
      
      <div className="ai-signature-details">
        <div className="detail-row">
          <span className="detail-label">Engine:</span>
          <span className="detail-value">{getEngineLabel(signature.ai_engine)}</span>
        </div>
        
        <div className="detail-row">
          <span className="detail-label">Model:</span>
          <span className="detail-value">{signature.model_name}</span>
        </div>
        
        {signature.model_version && (
          <div className="detail-row">
            <span className="detail-label">Version:</span>
            <span className="detail-value">{signature.model_version}</span>
          </div>
        )}
        
        <div className="detail-row">
          <span className="detail-label">Generated:</span>
          <span className="detail-value">{formatDate(signature.generated_at)}</span>
        </div>
        
        <div className="detail-row">
          <span className="detail-label">Key Mode:</span>
          <span className={`detail-value key-mode ${signature.key_mode}`}>
            {signature.key_mode === 'system' ? '🔐 System Key' : '🔑 Custom Key'}
          </span>
        </div>
        
        {signature.generation_id && (
          <div className="detail-row">
            <span className="detail-label">Generation ID:</span>
            <span className="detail-value mono">{signature.generation_id}</span>
          </div>
        )}
        
        {(signature.temperature !== undefined || signature.max_tokens !== undefined) && (
          <div className="detail-row">
            <span className="detail-label">Parameters:</span>
            <span className="detail-value">
              {signature.temperature !== undefined && `temp: ${signature.temperature}`}
              {signature.temperature !== undefined && signature.max_tokens !== undefined && ', '}
              {signature.max_tokens !== undefined && `max_tokens: ${signature.max_tokens}`}
            </span>
          </div>
        )}
      </div>

      <style jsx>{`
        .ai-signature-full {
          background: var(--bg-tertiary, #fafafa);
          border: 1px solid var(--border-color, #e0e0e0);
          border-radius: 8px;
          padding: 1rem;
          margin: 0.5rem 0;
        }
        .ai-signature-header {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          margin-bottom: 0.75rem;
          padding-bottom: 0.5rem;
          border-bottom: 1px solid var(--border-color, #e0e0e0);
        }
        .ai-icon {
          font-size: 1.25rem;
        }
        .ai-label {
          font-weight: 600;
          color: var(--text-primary, #333);
          font-size: 0.875rem;
        }
        .ai-signature-details {
          display: grid;
          gap: 0.375rem;
        }
        .detail-row {
          display: flex;
          align-items: baseline;
          gap: 0.5rem;
          font-size: 0.8125rem;
        }
        .detail-label {
          color: var(--text-secondary, #666);
          min-width: 90px;
        }
        .detail-value {
          color: var(--text-primary, #333);
          font-weight: 500;
        }
        .detail-value.mono {
          font-family: monospace;
          font-size: 0.75rem;
          background: var(--bg-secondary, #f0f0f0);
          padding: 0.125rem 0.375rem;
          border-radius: 3px;
        }
        .key-mode.system {
          color: #1565c0;
        }
        .key-mode.custom {
          color: #7b1fa2;
        }
      `}</style>
    </div>
  );
}

export default AISignatureDisplay;
