"""Self-hostable open-source model catalog.

A curated reference of open-source LLMs that can be deployed on the
memdog model server (Ollama / Cloud Run B) or via external
inference APIs.

Each entry describes hardware requirements, capabilities, benchmark scores,
and recommended roles. Each model has a ``gcs_filename`` (storage path in the
models bucket or /models volume) and a ``tier`` (small | medium | large | very-large)
so the catalog and UI know which inference tier to launch it on. Tiers map to
Cloud Run resources: small (2 vCPU / 6 GB), medium (4 vCPU / 12 GB), large (8 vCPU / 24 GB),
very-large (8 vCPU / 32 GB). ``memory_required_gb`` should align with tier limits.

Exposed via ``GET /api/v1/ai/model-catalog``.
"""

from typing import Any

# ---------------------------------------------------------------------------
# Catalog
# ---------------------------------------------------------------------------

SELF_HOSTABLE_MODELS: dict[str, dict[str, Any]] = {

    # ─────────────────────────────────────────────
    # MISTRAL FAMILY
    # ─────────────────────────────────────────────

    "mistral-7b": {
        "name": "Mistral 7B",
        "family": "mistral",
        "capability": "Strong general reasoning, instruction following, structured data tasks",
        "param_size": "7B",
        "context_window": 32768,
        "memory_required_gb": 6,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 80,
        "recommended_role": "leaf",
        "best_for": ["summarization", "data extraction", "classification"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "French", "German", "Spanish", "Italian"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI", "llama.cpp"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.10, "output": 0.30},
        "license": "Apache 2.0",
        "avg_latency_ms": 400,
        "benchmark_scores": {"MMLU": 62.5, "GSM8K": 52.1, "HumanEval": 30.5},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "mistral-7b-instruct-Q4_K_M.gguf",
    },

    "mistral-nemo-12b": {
        "name": "Mistral Nemo 12B",
        "family": "mistral",
        "capability": "Enhanced reasoning over 7B, good for multi-step data analysis",
        "param_size": "12B",
        "context_window": 128000,
        "memory_required_gb": 10,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 55,
        "recommended_role": "mid-tier",
        "best_for": ["multi-step reasoning", "long context analysis", "data summarization"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "French", "German", "Spanish", "Italian", "Portuguese"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.15, "output": 0.40},
        "license": "Apache 2.0",
        "avg_latency_ms": 600,
        "benchmark_scores": {"MMLU": 68.0, "GSM8K": 60.2, "HumanEval": 38.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "mistral-nemo-12b-instruct-Q4_K_M.gguf",
    },

    "mixtral-8x7b": {
        "name": "Mixtral 8x7B (MoE)",
        "family": "mistral",
        "capability": "Sparse mixture-of-experts, high quality at lower active compute cost",
        "param_size": "47B total / 13B active",
        "context_window": 32768,
        "memory_required_gb": 26,
        "tier": "very-large",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 45,
        "recommended_role": "mid-tier",
        "best_for": ["complex reasoning", "code generation", "multi-task pipelines"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "French", "German", "Spanish", "Italian"],
        "fine_tune_friendly": True,
        "inference_backend": ["vLLM", "TGI", "Ollama"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.24, "output": 0.24},
        "license": "Apache 2.0",
        "avg_latency_ms": 800,
        "benchmark_scores": {"MMLU": 70.6, "GSM8K": 74.4, "HumanEval": 40.2},
        "temperature_sweet_spot": 0.4,
        "gcs_filename": "mixtral-8x7b-instruct-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # META LLAMA FAMILY
    # ─────────────────────────────────────────────

    "llama-3.2-1b": {
        "name": "Llama 3.2 1B",
        "family": "llama",
        "capability": "Ultra-lightweight, edge inference, simple classification tasks",
        "param_size": "1B",
        "context_window": 131072,
        "memory_required_gb": 1.5,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 200,
        "recommended_role": "leaf",
        "best_for": ["classification", "entity extraction", "routing decisions"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": False,
        "languages": ["English"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Llama 3.2 Community",
        "avg_latency_ms": 100,
        "benchmark_scores": {"MMLU": 32.2, "GSM8K": 14.0, "HumanEval": 12.0},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "llama-3.2-1b-instruct-Q4_K_M.gguf",
    },

    "llama-3.2-3b": {
        "name": "Llama 3.2 3B",
        "family": "llama",
        "capability": "Lightweight, fast inference, basic data extraction and parsing",
        "param_size": "3B",
        "context_window": 131072,
        "memory_required_gb": 3,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 150,
        "recommended_role": "leaf",
        "best_for": ["data parsing", "simple extraction", "fast classification"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "German", "French", "Italian", "Portuguese", "Hindi", "Spanish"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Llama 3.2 Community",
        "avg_latency_ms": 200,
        "benchmark_scores": {"MMLU": 55.0, "GSM8K": 45.0, "HumanEval": 22.0},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "llama-3.2-3b-instruct-Q4_K_M.gguf",
    },

    "llama-3.1-8b": {
        "name": "Llama 3.1 8B",
        "family": "llama",
        "capability": "Solid instruction following, analytical tasks, good pipeline workhorse",
        "param_size": "8B",
        "context_window": 131072,
        "memory_required_gb": 7,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 80,
        "recommended_role": "leaf",
        "best_for": ["instruction following", "data analysis", "summarization", "JSON output"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "German", "French", "Italian", "Portuguese", "Hindi", "Spanish", "Thai"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI", "llama.cpp"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.05, "output": 0.08},
        "license": "Llama 3.1 Community",
        "avg_latency_ms": 350,
        "benchmark_scores": {"MMLU": 66.7, "GSM8K": 75.3, "HumanEval": 72.6},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "llama-3.1-8b-instruct-Q4_K_M.gguf",
    },

    "llama-3.3-70b": {
        "name": "Llama 3.3 70B",
        "family": "llama",
        "capability": "Mid-tier orchestration, complex reasoning, near frontier quality",
        "param_size": "70B",
        "context_window": 131072,
        "memory_required_gb": 48,
        "tier": "very-large",
        "quantization_support": ["Q4", "Q8", "AWQ", "GPTQ"],
        "speed_tokens_per_sec": 25,
        "recommended_role": "orchestrator",
        "best_for": ["orchestration", "complex reasoning", "agentic planning", "code generation"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "German", "French", "Italian", "Portuguese", "Hindi", "Spanish"],
        "fine_tune_friendly": True,
        "inference_backend": ["vLLM", "TGI", "Groq API"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.23, "output": 0.40},
        "license": "Llama 3.3 Community",
        "avg_latency_ms": 1200,
        "benchmark_scores": {"MMLU": 86.0, "GSM8K": 91.1, "HumanEval": 88.4},
        "temperature_sweet_spot": 0.4,
        "gcs_filename": "llama-3.3-70b-instruct-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # GOOGLE GEMMA FAMILY
    # ─────────────────────────────────────────────

    "gemma-2-2b": {
        "name": "Gemma 2 2B",
        "family": "gemma",
        "capability": "Extremely efficient, Apache 2.0, good for fast lightweight inference",
        "param_size": "2B",
        "context_window": 8192,
        "memory_required_gb": 2,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 160,
        "recommended_role": "leaf",
        "best_for": ["fast classification", "simple QA", "text parsing"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": False,
        "languages": ["English"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 150,
        "benchmark_scores": {"MMLU": 51.3, "GSM8K": 23.9, "HumanEval": 18.0},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "gemma-2-2b-it-Q4_K_M.gguf",
    },

    "gemma-2-9b": {
        "name": "Gemma 2 9B",
        "family": "gemma",
        "capability": "Strong reasoning for size, great for structured analytical pipelines",
        "param_size": "9B",
        "context_window": 8192,
        "memory_required_gb": 8,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 70,
        "recommended_role": "mid-tier",
        "best_for": ["structured analysis", "data reasoning", "summarization"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 400,
        "benchmark_scores": {"MMLU": 70.4, "GSM8K": 68.6, "HumanEval": 40.2},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "gemma-2-9b-it-Q4_K_M.gguf",
    },

    "gemma-2-27b": {
        "name": "Gemma 2 27B",
        "family": "gemma",
        "capability": "Powerful mid-tier model with strong reasoning, instruction following, and multilingual support",
        "param_size": "27B",
        "context_window": 8192,
        "memory_required_gb": 20,
        "tier": "large",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 30,
        "recommended_role": "orchestrator",
        "best_for": ["complex reasoning", "agentic workflows", "data synthesis"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "multilingual 30+"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 700,
        "benchmark_scores": {"MMLU": 76.6, "GSM8K": 77.4, "HumanEval": 52.4},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "gemma-2-27b-it-Q4_K_M.gguf",
    },

    "gemma-3-27b": {
        "name": "Gemma 3 27B",
        "family": "gemma",
        "capability": "Powerful mid-tier model with vision support, strong reasoning, and multilingual capabilities",
        "param_size": "27B",
        "context_window": 131072,
        "memory_required_gb": 20,
        "tier": "large",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 30,
        "recommended_role": "orchestrator",
        "best_for": ["complex reasoning", "agentic workflows", "vision tasks", "data synthesis"],
        "supports_function_calling": True,
        "supports_multimodal": True,
        "supports_structured_output": True,
        "languages": ["English", "multilingual 30+"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 700,
        "benchmark_scores": {"MMLU": 76.6, "GSM8K": 77.4, "HumanEval": 52.4},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "gemma-3-27b-it-Q4_K_M.gguf",
    },

    "gemma-3-1b": {
        "name": "Gemma 3 1B",
        "family": "gemma",
        "capability": "Ultra-lightweight Gemma 3, fast inference, instruction following",
        "param_size": "1B",
        "context_window": 131072,
        "memory_required_gb": 2,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 180,
        "recommended_role": "leaf",
        "best_for": ["fast classification", "simple QA", "edge inference"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "multilingual 140+"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 120,
        "benchmark_scores": {"MMLU": 45.0, "GSM8K": 25.0, "HumanEval": 20.0},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "gemma-3-1b-it-Q4_K_M.gguf",
    },

    "gemma-3-12b": {
        "name": "Gemma 3 12B",
        "family": "gemma",
        "capability": "Mid-size Gemma 3 with vision, strong reasoning and multilingual support",
        "param_size": "12B",
        "context_window": 131072,
        "memory_required_gb": 10,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 55,
        "recommended_role": "mid-tier",
        "best_for": ["multimodal analysis", "reasoning", "data synthesis", "vision tasks"],
        "supports_function_calling": True,
        "supports_multimodal": True,
        "supports_structured_output": True,
        "languages": ["English", "multilingual 140+"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 500,
        "benchmark_scores": {"MMLU": 72.0, "GSM8K": 68.0, "HumanEval": 48.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "gemma-3-12b-it-Q4_K_M.gguf",
    },

    "gemma-3-4b": {
        "name": "Gemma 3 4B",
        "family": "gemma",
        "capability": "Multimodal support, fast inference, latest Google open model",
        "param_size": "4B",
        "context_window": 131072,
        "memory_required_gb": 4,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 110,
        "recommended_role": "leaf",
        "best_for": ["multimodal data", "image + text pipelines", "fast analysis"],
        "supports_function_calling": True,
        "supports_multimodal": True,
        "supports_structured_output": True,
        "languages": ["English", "multilingual 140+"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 250,
        "benchmark_scores": {"MMLU": 59.6, "GSM8K": 38.4, "HumanEval": 36.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "gemma-3-4b-it-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # MICROSOFT PHI FAMILY
    # ─────────────────────────────────────────────

    "phi-3-mini": {
        "name": "Phi-3 Mini 3.8B",
        "family": "phi",
        "capability": "Outstanding structured reasoning for its size, great for data pipelines",
        "param_size": "3.8B",
        "context_window": 128000,
        "memory_required_gb": 3.5,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF", "ONNX"],
        "speed_tokens_per_sec": 120,
        "recommended_role": "leaf",
        "best_for": ["structured reasoning", "data analysis", "math tasks"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "llama.cpp", "ONNX Runtime"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "MIT",
        "avg_latency_ms": 220,
        "benchmark_scores": {"MMLU": 68.8, "GSM8K": 82.5, "HumanEval": 58.9},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "phi-3-mini-128k-instruct-Q4_K_M.gguf",
    },

    "phi-4": {
        "name": "Phi-4 14B",
        "family": "phi",
        "capability": "Best-in-class for math, analytical, and data-heavy reasoning tasks",
        "param_size": "14B",
        "context_window": 16384,
        "memory_required_gb": 12,
        "tier": "large",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 50,
        "recommended_role": "mid-tier",
        "best_for": ["math reasoning", "data analysis", "scientific tasks", "structured output"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.07, "output": 0.14},
        "license": "MIT",
        "avg_latency_ms": 600,
        "benchmark_scores": {"MMLU": 84.8, "GSM8K": 91.2, "HumanEval": 82.6},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "phi-4-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # QWEN FAMILY (ALIBABA)
    # ─────────────────────────────────────────────

    "qwen2.5-0.5b": {
        "name": "Qwen 2.5 0.5B",
        "family": "qwen",
        "capability": "Smallest viable model, fast classification, multilingual support",
        "param_size": "0.5B",
        "context_window": 32768,
        "memory_required_gb": 1,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 300,
        "recommended_role": "leaf",
        "best_for": ["fast routing", "language detection", "simple classification"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": False,
        "languages": ["English", "Chinese", "multilingual 29+"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 80,
        "benchmark_scores": {"MMLU": 40.0, "GSM8K": 20.0, "HumanEval": 10.0},
        "temperature_sweet_spot": 0.1,
        "gcs_filename": "qwen2.5-0.5b-instruct-Q4_K_M.gguf",
    },

    "qwen2.5-1.5b": {
        "name": "Qwen 2.5 1.5B",
        "family": "qwen",
        "capability": "Lightweight multilingual analysis, structured output generation",
        "param_size": "1.5B",
        "context_window": 32768,
        "memory_required_gb": 2,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 220,
        "recommended_role": "leaf",
        "best_for": ["multilingual extraction", "structured output", "tagging"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "multilingual 29+"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 120,
        "benchmark_scores": {"MMLU": 55.0, "GSM8K": 42.0, "HumanEval": 28.0},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "qwen2.5-1.5b-instruct-Q4_K_M.gguf",
    },

    "qwen2.5-7b": {
        "name": "Qwen 2.5 7B",
        "family": "qwen",
        "capability": "Strong multilingual reasoning, code and data analysis",
        "param_size": "7B",
        "context_window": 131072,
        "memory_required_gb": 6,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 85,
        "recommended_role": "leaf",
        "best_for": ["multilingual analysis", "code tasks", "data reasoning", "JSON output"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "multilingual 29+"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.07, "output": 0.07},
        "license": "Apache 2.0",
        "avg_latency_ms": 350,
        "benchmark_scores": {"MMLU": 74.2, "GSM8K": 85.4, "HumanEval": 72.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "qwen2.5-7b-instruct-Q4_K_M.gguf",
    },

    "qwen2.5-coder-7b": {
        "name": "Qwen 2.5 Coder 7B",
        "family": "qwen",
        "capability": "Specialized for code and data tasks, SQL generation, data wrangling",
        "param_size": "7B",
        "context_window": 131072,
        "memory_required_gb": 6,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 85,
        "recommended_role": "leaf",
        "best_for": ["SQL generation", "data wrangling", "code analysis", "ETL scripting"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "code-focused"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.07, "output": 0.07},
        "license": "Apache 2.0",
        "avg_latency_ms": 350,
        "benchmark_scores": {"MMLU": 71.0, "GSM8K": 83.0, "HumanEval": 88.4},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "qwen2.5-coder-7b-instruct-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # DEEPSEEK FAMILY
    # ─────────────────────────────────────────────

    "deepseek-r1-distill-1.5b": {
        "name": "DeepSeek R1 Distill Qwen 1.5B",
        "family": "deepseek",
        "capability": "Chain-of-thought reasoning distilled into tiny model, cost-effective sub-tasks",
        "param_size": "1.5B",
        "context_window": 131072,
        "memory_required_gb": 2,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 200,
        "recommended_role": "leaf",
        "best_for": ["reasoning sub-tasks", "step-by-step analysis", "cheap CoT"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": False,
        "languages": ["English", "Chinese"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "MIT",
        "avg_latency_ms": 150,
        "benchmark_scores": {"MMLU": 28.9, "GSM8K": 28.9, "HumanEval": 20.0},
        "temperature_sweet_spot": 0.1,
        "gcs_filename": "deepseek-r1-distill-qwen-1.5b-Q4_K_M.gguf",
    },

    "deepseek-r1-distill-7b": {
        "name": "DeepSeek R1 Distill Qwen 7B",
        "family": "deepseek",
        "capability": "Best bang-for-buck reasoning model, strong analytical sub-task handling",
        "param_size": "7B",
        "context_window": 131072,
        "memory_required_gb": 6,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 85,
        "recommended_role": "leaf",
        "best_for": ["analytical reasoning", "data analysis", "summarization", "math"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.14, "output": 0.28},
        "license": "MIT",
        "avg_latency_ms": 380,
        "benchmark_scores": {"MMLU": 55.5, "GSM8K": 87.3, "HumanEval": 55.0},
        "temperature_sweet_spot": 0.1,
        "gcs_filename": "deepseek-r1-distill-qwen-7b-Q4_K_M.gguf",
    },

    "deepseek-r1-distill-8b": {
        "name": "DeepSeek R1 Distill Llama 8B",
        "family": "deepseek",
        "capability": "Llama-based reasoning distill, drop-in for Llama stacks with reasoning boost",
        "param_size": "8B",
        "context_window": 131072,
        "memory_required_gb": 7,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 80,
        "recommended_role": "leaf",
        "best_for": ["reasoning tasks", "data analysis", "llama-compatible stacks"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "MIT",
        "avg_latency_ms": 400,
        "benchmark_scores": {"MMLU": 60.0, "GSM8K": 89.1, "HumanEval": 50.4},
        "temperature_sweet_spot": 0.1,
        "gcs_filename": "deepseek-r1-distill-llama-8b-Q4_K_M.gguf",
    },

    "deepseek-r1-distill-14b": {
        "name": "DeepSeek R1 Distill Qwen 14B",
        "family": "deepseek",
        "capability": "Mid-tier orchestration with strong reasoning, good cost-quality balance",
        "param_size": "14B",
        "context_window": 131072,
        "memory_required_gb": 12,
        "tier": "large",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 45,
        "recommended_role": "mid-tier",
        "best_for": ["complex reasoning", "orchestration support", "multi-step data tasks"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.14, "output": 0.28},
        "license": "MIT",
        "avg_latency_ms": 700,
        "benchmark_scores": {"MMLU": 69.7, "GSM8K": 93.9, "HumanEval": 69.5},
        "temperature_sweet_spot": 0.1,
        "gcs_filename": "deepseek-r1-distill-qwen-14b-Q4_K_M.gguf",
    },

    "deepseek-r1-distill-32b": {
        "name": "DeepSeek R1 Distill Qwen 32B",
        "family": "deepseek",
        "capability": "Near frontier reasoning, suitable for complex orchestration layers",
        "param_size": "32B",
        "context_window": 131072,
        "memory_required_gb": 24,
        "tier": "very-large",
        "quantization_support": ["Q4", "Q8", "AWQ", "GPTQ"],
        "speed_tokens_per_sec": 25,
        "recommended_role": "orchestrator",
        "best_for": ["complex orchestration", "deep reasoning", "agentic planning"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese"],
        "fine_tune_friendly": True,
        "inference_backend": ["vLLM", "TGI", "Ollama"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.14, "output": 0.28},
        "license": "MIT",
        "avg_latency_ms": 1100,
        "benchmark_scores": {"MMLU": 72.6, "GSM8K": 95.6, "HumanEval": 72.6},
        "temperature_sweet_spot": 0.1,
        "gcs_filename": "deepseek-r1-distill-qwen-32b-Q4_K_M.gguf",
    },

    "deepseek-v3": {
        "name": "DeepSeek V3",
        "family": "deepseek",
        "capability": "685B MoE with 37B active params, excellent for code, data analysis, structured output",
        "param_size": "685B total / 37B active",
        "context_window": 131072,
        "memory_required_gb": 80,
        "tier": "very-large",
        "quantization_support": ["Q4", "Q8", "FP8"],
        "speed_tokens_per_sec": 30,
        "recommended_role": "orchestrator",
        "best_for": ["orchestration", "code generation", "complex data analysis", "long context tasks"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "multilingual"],
        "fine_tune_friendly": False,
        "inference_backend": ["DeepSeek API", "vLLM (multi-GPU)"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.27, "output": 1.10},
        "license": "MIT",
        "avg_latency_ms": 1500,
        "benchmark_scores": {"MMLU": 88.5, "GSM8K": 97.5, "HumanEval": 90.2},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "deepseek-v3-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # QWEN3 FAMILY
    # ─────────────────────────────────────────────

    "qwen3-8b": {
        "name": "Qwen 3 8B",
        "family": "qwen",
        "capability": "Strong general and coding performance, parameter-efficient, fast inference",
        "param_size": "8B",
        "context_window": 131072,
        "memory_required_gb": 6,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 85,
        "recommended_role": "leaf",
        "best_for": ["general chat", "code", "reasoning", "multilingual analysis"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "multilingual"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.07, "output": 0.07},
        "license": "Apache 2.0",
        "avg_latency_ms": 350,
        "benchmark_scores": {"MMLU": 76.0, "GSM8K": 88.0, "HumanEval": 75.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "qwen3-8b-Q4_K_M.gguf",
    },

    "qwen3-32b": {
        "name": "Qwen 3 32B",
        "family": "qwen",
        "capability": "High-quality reasoning and coding, Qwen3-Next series",
        "param_size": "32B",
        "context_window": 131072,
        "memory_required_gb": 24,
        "tier": "very-large",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 28,
        "recommended_role": "orchestrator",
        "best_for": ["complex reasoning", "code generation", "orchestration", "agentic tasks"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "multilingual"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.14, "output": 0.14},
        "license": "Apache 2.0",
        "avg_latency_ms": 1000,
        "benchmark_scores": {"MMLU": 82.0, "GSM8K": 92.0, "HumanEval": 82.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "qwen3-32b-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # IBM GRANITE FAMILY
    # ─────────────────────────────────────────────

    "granite4-tiny": {
        "name": "Granite 4 Tiny",
        "family": "granite",
        "capability": "IBM enterprise model (tiny MoE), tool-calling, instruction following",
        "param_size": "~7B (MoE tiny)",
        "context_window": 131072,
        "memory_required_gb": 6,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 75,
        "recommended_role": "leaf",
        "best_for": ["enterprise tasks", "tool use", "instruction following", "multilingual"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "German", "Spanish", "French", "Japanese", "Portuguese", "Arabic", "Czech", "Italian", "Korean", "Dutch", "Chinese"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 380,
        "benchmark_scores": {"MMLU": 68.0, "GSM8K": 72.0, "HumanEval": 45.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "granite4-tiny-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # CODELlAMA FAMILY (META)
    # ─────────────────────────────────────────────

    "codellama-7b": {
        "name": "CodeLlama 7B Instruct",
        "family": "codellama",
        "capability": "Meta code model, code completion and instruction following",
        "param_size": "7B",
        "context_window": 16384,
        "memory_required_gb": 5,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 80,
        "recommended_role": "leaf",
        "best_for": ["code completion", "code analysis", "SQL", "data scripting"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "code-focused"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.06, "output": 0.08},
        "license": "Llama 2 Community",
        "avg_latency_ms": 360,
        "benchmark_scores": {"MMLU": 53.0, "GSM8K": 35.0, "HumanEval": 35.4},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "codellama-7b-instruct-Q4_K_M.gguf",
    },

    "codellama-34b": {
        "name": "CodeLlama 34B Instruct",
        "family": "codellama",
        "capability": "Meta premier coding model, 87% code completion accuracy",
        "param_size": "34B",
        "context_window": 16384,
        "memory_required_gb": 22,
        "tier": "very-large",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 30,
        "recommended_role": "mid-tier",
        "best_for": ["code generation", "refactoring", "multi-file code", "80+ languages"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "code-focused"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.18, "output": 0.25},
        "license": "Llama 2 Community",
        "avg_latency_ms": 900,
        "benchmark_scores": {"MMLU": 62.0, "GSM8K": 55.0, "HumanEval": 48.0},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "codellama-34b-instruct-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # MEDICAL / BIOMEDICAL FAMILY
    # ─────────────────────────────────────────────

    "biomistral-7b": {
        "name": "BioMistral 7B",
        "family": "medical",
        "capability": "Biomedical LLM, PubMed-trained, medical QA and literature",
        "param_size": "7B",
        "context_window": 32768,
        "memory_required_gb": 6,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 75,
        "recommended_role": "leaf",
        "best_for": ["medical QA", "biomedical literature", "clinical data analysis", "research"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 400,
        "benchmark_scores": {"MMLU": 65.0, "MedQA": 52.0, "PubMedQA": 78.0},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "biomistral-7b-Q4_K_M.gguf",
    },

    "medicine-llm-13b": {
        "name": "Medicine LLM 13B",
        "family": "medical",
        "capability": "AdaptLLM medicine model, clinical and medicine QA",
        "param_size": "13B",
        "context_window": 4096,
        "memory_required_gb": 10,
        "tier": "large",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 50,
        "recommended_role": "mid-tier",
        "best_for": ["clinical QA", "medicine QA", "medical data analysis", "research"],
        "supports_function_calling": False,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Custom (AdaptLLM)",
        "avg_latency_ms": 600,
        "benchmark_scores": {"MMLU": 58.0, "MedQA": 48.0, "PubMedQA": 72.0},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "medicine-llm-13b-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # INTERNLM FAMILY (SHANGHAI AI LAB)
    # ─────────────────────────────────────────────

    "internlm2.5-7b": {
        "name": "InternLM 2.5 7B Chat (1M context)",
        "family": "internlm",
        "capability": "Long-context chat, 1M tokens, strong instruction following",
        "param_size": "7B",
        "context_window": 1048576,
        "memory_required_gb": 6,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 80,
        "recommended_role": "leaf",
        "best_for": ["long documents", "RAG", "chat", "tool use"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "multilingual"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.06, "output": 0.08},
        "license": "InternLM2 License",
        "avg_latency_ms": 370,
        "benchmark_scores": {"MMLU": 78.0, "GSM8K": 82.0, "HumanEval": 65.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "internlm2.5-7b-chat-1m-Q4_K_M.gguf",
    },

    "internlm2.5-20b": {
        "name": "InternLM 2.5 20B Chat",
        "family": "internlm",
        "capability": "Strong chat and reasoning, 32K context",
        "param_size": "20B",
        "context_window": 32768,
        "memory_required_gb": 14,
        "tier": "large",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 45,
        "recommended_role": "mid-tier",
        "best_for": ["complex chat", "reasoning", "code", "data analysis"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "multilingual"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.12, "output": 0.16},
        "license": "InternLM2 License",
        "avg_latency_ms": 650,
        "benchmark_scores": {"MMLU": 82.0, "GSM8K": 88.0, "HumanEval": 72.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "internlm2.5-20b-chat-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # YI FAMILY (01.AI)
    # ─────────────────────────────────────────────

    "yi-1.5-9b": {
        "name": "Yi 1.5 9B Chat",
        "family": "yi",
        "capability": "Strong multilingual and coding, 01.AI open model",
        "param_size": "9B",
        "context_window": 32768,
        "memory_required_gb": 6,
        "tier": "medium",
        "quantization_support": ["Q4", "Q8", "GGUF", "AWQ"],
        "speed_tokens_per_sec": 78,
        "recommended_role": "leaf",
        "best_for": ["multilingual chat", "code", "reasoning", "instruction following"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "multilingual"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "llama.cpp"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.06, "output": 0.08},
        "license": "Yi Community",
        "avg_latency_ms": 380,
        "benchmark_scores": {"MMLU": 76.0, "GSM8K": 82.0, "HumanEval": 68.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "yi-1.5-9b-chat-Q4_K_M.gguf",
    },

    "yi-1.5-34b": {
        "name": "Yi 1.5 34B Chat",
        "family": "yi",
        "capability": "Large Yi 1.5, strong reasoning and coding",
        "param_size": "34B",
        "context_window": 32768,
        "memory_required_gb": 24,
        "tier": "very-large",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 28,
        "recommended_role": "orchestrator",
        "best_for": ["complex reasoning", "code generation", "multilingual", "agentic tasks"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English", "Chinese", "multilingual"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "vLLM", "TGI"],
        "self_hostable": True,
        "api_available": True,
        "api_cost_per_1m_tokens": {"input": 0.20, "output": 0.28},
        "license": "Yi Community",
        "avg_latency_ms": 950,
        "benchmark_scores": {"MMLU": 80.0, "GSM8K": 88.0, "HumanEval": 75.0},
        "temperature_sweet_spot": 0.3,
        "gcs_filename": "yi-1.5-34b-chat-Q4_K_M.gguf",
    },

    # ─────────────────────────────────────────────
    # SMOLLM FAMILY (HUGGING FACE)
    # ─────────────────────────────────────────────

    "smollm2-1.7b": {
        "name": "SmolLM2 1.7B Instruct",
        "family": "smollm",
        "capability": "State-of-the-art compact LLM, on-device and edge",
        "param_size": "1.7B",
        "context_window": 8192,
        "memory_required_gb": 2,
        "tier": "small",
        "quantization_support": ["Q4", "Q8", "GGUF"],
        "speed_tokens_per_sec": 200,
        "recommended_role": "leaf",
        "best_for": ["edge inference", "fast classification", "summarization", "routing"],
        "supports_function_calling": True,
        "supports_multimodal": False,
        "supports_structured_output": True,
        "languages": ["English"],
        "fine_tune_friendly": True,
        "inference_backend": ["Ollama", "llama.cpp"],
        "self_hostable": True,
        "api_available": False,
        "api_cost_per_1m_tokens": None,
        "license": "Apache 2.0",
        "avg_latency_ms": 150,
        "benchmark_scores": {"MMLU": 52.0, "GSM8K": 42.0, "HumanEval": 28.0},
        "temperature_sweet_spot": 0.2,
        "gcs_filename": "smollm2-1.7b-instruct-Q4_K_M.gguf",
    },
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

FAMILIES: list[str] = sorted({m["family"] for m in SELF_HOSTABLE_MODELS.values()})
ROLES: list[str] = ["leaf", "mid-tier", "orchestrator"]


def get_by_family(family: str) -> dict[str, dict]:
    """Return all models for a given family."""
    return {k: v for k, v in SELF_HOSTABLE_MODELS.items() if v["family"] == family}


def get_by_role(role: str) -> dict[str, dict]:
    """Return all models with a given recommended_role."""
    return {k: v for k, v in SELF_HOSTABLE_MODELS.items() if v["recommended_role"] == role}


def get_by_memory(max_gb: float) -> dict[str, dict]:
    """Return all models whose memory_required_gb <= max_gb."""
    return {k: v for k, v in SELF_HOSTABLE_MODELS.items() if v["memory_required_gb"] <= max_gb}
