"""Static provider catalog for Model Garden.

Each entry describes an AI provider's metadata, authentication requirements,
API endpoints for model discovery, and well-known default models.
"""

from __future__ import annotations

from app.models import ProviderInfo

PROVIDER_REGISTRY: dict[str, ProviderInfo] = {
    "openai": ProviderInfo(
        engine_type="openai",
        display_name="OpenAI",
        description="GPT-4o, GPT-4, GPT-3.5, DALL-E, and embedding models",
        icon="openai",
        requires_api_key=True,
        default_base_url="https://api.openai.com/v1",
        api_key_placeholder="sk-...",
        litellm_prefix="openai/",
        auth_header="Authorization",
        auth_scheme="Bearer",
        models_endpoint="/models",
        default_models=["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo"],
        default_embedding_models=["text-embedding-3-small", "text-embedding-3-large"],
        category="cloud",
    ),
    "anthropic": ProviderInfo(
        engine_type="anthropic",
        display_name="Anthropic",
        description="Claude 4, Claude 3.5, and Claude 3 model family",
        icon="anthropic",
        requires_api_key=True,
        default_base_url="https://api.anthropic.com",
        api_key_placeholder="sk-ant-...",
        litellm_prefix="anthropic/",
        auth_header="x-api-key",
        auth_scheme="",
        models_endpoint="/v1/models",
        default_models=["claude-sonnet-4-20250514", "claude-haiku-4-20250414", "claude-3-5-sonnet-20241022"],
        default_embedding_models=[],
        category="cloud",
    ),
    "gemini": ProviderInfo(
        engine_type="gemini",
        display_name="Google Gemini",
        description="Gemini Pro, Flash, and embedding models via Google AI Studio",
        icon="gemini",
        requires_api_key=True,
        default_base_url="https://generativelanguage.googleapis.com",
        api_key_placeholder="AIza...",
        litellm_prefix="gemini/",
        auth_header="",
        auth_scheme="",
        models_endpoint="/v1beta/models",
        default_models=["gemini-2.5-flash-preview-05-20", "gemini-2.5-pro-preview-05-06", "gemini-3.1-pro-preview"],
        default_embedding_models=["text-embedding-004"],
        category="cloud",
    ),
    "ollama": ProviderInfo(
        engine_type="ollama",
        display_name="Ollama (Local)",
        description="Run open-source models locally via Ollama",
        icon="ollama",
        requires_api_key=False,
        default_base_url="http://localhost:11434",
        api_key_placeholder=None,
        litellm_prefix="ollama/",
        auth_header="",
        auth_scheme="",
        models_endpoint="/api/tags",
        default_models=["llama3.1", "gemma3:12b", "mistral", "qwen3:8b"],
        default_embedding_models=["nomic-embed-text", "mxbai-embed-large"],
        category="local",
    ),
    "ollama_cloud": ProviderInfo(
        engine_type="ollama_cloud",
        display_name="Ollama Cloud",
        description="Run open-source models on Ollama's cloud infrastructure",
        icon="ollama_cloud",
        requires_api_key=True,
        default_base_url="https://api.ollama.com",
        api_key_placeholder="ollama-cloud-key...",
        litellm_prefix="ollama/",
        auth_header="Authorization",
        auth_scheme="Bearer",
        models_endpoint="/api/tags",
        default_models=["llama3.1", "gemma3:12b", "mistral", "qwen3:8b", "deepseek-r1"],
        default_embedding_models=["nomic-embed-text", "mxbai-embed-large"],
        category="cloud",
    ),
    "openrouter": ProviderInfo(
        engine_type="openrouter",
        display_name="OpenRouter",
        description="Access 100+ models from multiple providers through one API",
        icon="openrouter",
        requires_api_key=True,
        default_base_url="https://openrouter.ai/api",
        api_key_placeholder="sk-or-...",
        litellm_prefix="openrouter/",
        auth_header="Authorization",
        auth_scheme="Bearer",
        models_endpoint="/v1/models",
        default_models=["openai/gpt-4o", "anthropic/claude-sonnet-4", "google/gemini-2.5-flash"],
        default_embedding_models=[],
        category="cloud",
    ),
    "together": ProviderInfo(
        engine_type="together",
        display_name="Together AI",
        description="Fast inference for open-source models (Llama, Mixtral, etc.)",
        icon="together",
        requires_api_key=True,
        default_base_url="https://api.together.xyz",
        api_key_placeholder="tok-...",
        litellm_prefix="together_ai/",
        auth_header="Authorization",
        auth_scheme="Bearer",
        models_endpoint="/v1/models",
        default_models=["meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo", "mistralai/Mixtral-8x7B-Instruct-v0.1"],
        default_embedding_models=["togethercomputer/m2-bert-80M-8k-retrieval"],
        category="cloud",
    ),
    "huggingface": ProviderInfo(
        engine_type="huggingface",
        display_name="Hugging Face",
        description="Inference API for thousands of open-source models",
        icon="huggingface",
        requires_api_key=True,
        default_base_url="https://api-inference.huggingface.co",
        api_key_placeholder="hf_...",
        litellm_prefix="huggingface/",
        auth_header="Authorization",
        auth_scheme="Bearer",
        models_endpoint="/api/models",
        default_models=["meta-llama/Meta-Llama-3-8B-Instruct", "mistralai/Mistral-7B-Instruct-v0.3"],
        default_embedding_models=["sentence-transformers/all-MiniLM-L6-v2"],
        category="cloud",
    ),
    "bedrock": ProviderInfo(
        engine_type="bedrock",
        display_name="Amazon Bedrock",
        description="AWS-managed foundation models (Claude, Titan, Llama)",
        icon="bedrock",
        requires_api_key=True,
        default_base_url=None,
        api_key_placeholder="AWS credentials required",
        litellm_prefix="bedrock/",
        auth_header="",
        auth_scheme="",
        models_endpoint=None,
        default_models=["anthropic.claude-3-sonnet-20240229-v1:0", "amazon.titan-text-express-v1"],
        default_embedding_models=["amazon.titan-embed-text-v2:0"],
        category="cloud",
    ),
    "vllm": ProviderInfo(
        engine_type="vllm",
        display_name="vLLM",
        description="High-throughput self-hosted inference engine",
        icon="vllm",
        requires_api_key=False,
        default_base_url="http://localhost:8000",
        api_key_placeholder=None,
        litellm_prefix="openai/",
        auth_header="Authorization",
        auth_scheme="Bearer",
        models_endpoint="/v1/models",
        default_models=[],
        default_embedding_models=[],
        category="local",
    ),
    "litellm": ProviderInfo(
        engine_type="litellm",
        display_name="LiteLLM Gateway",
        description="Unified proxy gateway supporting 100+ LLM providers",
        icon="litellm",
        requires_api_key=False,
        default_base_url="http://localhost:4000",
        api_key_placeholder="sk-...",
        litellm_prefix="",
        auth_header="Authorization",
        auth_scheme="Bearer",
        models_endpoint="/models",
        default_models=[],
        default_embedding_models=[],
        category="gateway",
    ),
}


def get_registry() -> dict[str, ProviderInfo]:
    """Return the full provider registry."""
    return PROVIDER_REGISTRY


def get_provider(engine_type: str) -> ProviderInfo | None:
    """Return provider info for a specific engine type."""
    return PROVIDER_REGISTRY.get(engine_type)
