apiVersion: v1
kind: Service
metadata:
  name: webhook-gateway
  namespace: webhook-gateway
  labels:
    app: webhook-gateway
    app.kubernetes.io/part-of: mem-dog
    app.kubernetes.io/component: webhook-gateway
spec:
  type: ClusterIP
  selector:
    app: webhook-gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
